### ISSUE TITLE
Explain us the benefits of linting in the PWA

### ISSUE THREAD

**Issue by jometzner** [intershop/intershop-dev-community#14]
In current PWA we have a couple of linter rules enabled and implemented to annoy every developer. Ooops did I write this? No honestly explain us the advantages of linting in my project's codebase.

**Comment by shauke** [comment]
Besides the ESLint/TSLint rules and linting also the Stylelint integration should be shown and discussed.

**Comment by MaxKless** [comment]
The presentation PDF is now uploaded to the presentations folder :)

**Comment by jometzner** [comment]
YouTube Link is here https://youtu.be/kj48ddf-iTI
