### ISSUE TITLE
Introduction to Tomcat 9

### ISSUE THREAD

**Issue by jometzner** [intershop/intershop-dev-community#3]
With Intershop Commerce Management 7.10.31 Apache Tomcat 9 has been integrated. Please, shed some light on how this effects my project solutions.

**Comment by jometzner** [comment]
Here is a list of things we should cover in a talk/open discussion:
- No internal/external tomcat deployment anymore
- Solr4 deployment to external tomcat is no longer possible
- ICM application server startup has changed
- Encoding issues needed to be fixed

**Comment by bambucks** [comment]
I tried to upgrade to the TomCat 9 version but had to rollback into the lower ICM version because I have some injections error, spent a day or so with no resolution.
